### ISSUE TITLE
Vulkan API Support

### ISSUE THREAD

**Issue by fivefeet8** [devmiyax/yabause#178]
Any plans to support the Vulkan API? 

https://developer.nvidia.com/vulkan-android#samples

**Comment by devmiyax** [comment]
Sure!

**Comment by ADormant** [comment]
Yes Vulkan would be great because it has the same compatibility between desktop and mobile.

https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#introduction
https://github.com/KhronosGroup
https://www.khronos.org/news/press/khronos-releases-vulkan-1-0-specification
https://www.khronos.org/registry/vulkan/
https://github.com/SaschaWillems/Vulkan
https://github.com/vlj/rpcs3/tree/vulkan

**Comment by ADormant** [comment]
http://developer.download.nvidia.com/assets/gameworks/downloads/secure/Vulkan_Beta_Drivers/GL_NV_draw_vulkan_image.txt?autho=1455669688_460483b6163765dab8b29fe76145a80e&file=GL_NV_draw_vulkan_image.txt

**Comment by ADormant** [comment]
@devmiyax 
https://github.com/nvpro-pipeline/vkcpp
https://github.com/john-chapman/VulkanTest
https://github.com/mlaveaux/VulkanRenderer
https://github.com/pld-linux/vulkan-loader
https://github.com/FaultyRAM/vulkan-sys
https://github.com/kainino0x/rust-vulkan

**Comment by fivefeet8** [comment]
Nvidia Shield TV OTA with Vulkan support updated.  

[url=http://postimg.org/image/tid3t5ubd/][img]http://s28.postimg.org/tid3t5ubd/Threaded_Rendering_Vk_20160222_090825.jpg[/img][/url]

Running on my Shield TV using the Vulkan APi.

**Comment by ADormant** [comment]
https://github.com/tomaka/vulkano

**Comment by devmiyax** [comment]
done
