### ISSUE TITLE
[Mortal Kombat] Kind of Zoom !!!

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#363]
Left Picture : UoYabause 0.4.6
Right Picture : SSF Test Version (last build)

![moratl kombat 2](https://cloud.githubusercontent.com/assets/12481242/25761974/1fd63c08-31dd-11e7-82a5-fd86eb41d267.JPG)

**Comment by FCare** [comment]
It is due to lack of transformation between saturn resolution and openGL native window. It is the same issue as the deformation in full screen mode. I think it happens only on GLFW and QT port since Android port might take care of this. I will look to fix for GLFW port. If someone wants to fix for QT port, he is welcome :-)

**Comment by BenjaminSiskoo** [comment]
UoYabause 0.5.2 commit 4106 :  same problem

Problem with the option fit to window, there is a kind of zoom with.

**Comment by BenjaminSiskoo** [comment]
Same problem with Yaba Sanshiro 1.3.0 RC
