### ISSUE TITLE
SIGSEGV: invalid address (fault address: 0xd0)

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#367]
New Dynarec crashes in a strange way.

* thread #27, name = 'yabause.android', stop reason = signal SIGSEGV: invalid address (fault address: 0xd0)
  * frame #0: 0xc271014c

```
0xc271014c: str r8, [r7, #0x58] <-- Crash!
```

```
  r4 = 0xca8ff920
  r5 = 0xeb4df07d libc.so`__pthread_start(void*) + 1
  r6 = 0xca8ff920
  r7 = 0x00000078 <-- broken!
  r8 = 0xc91ff714 libyabause_native.so`_threadId
  r9 = 0x00000000
  r10 = 0xc6dc4600 libyabause_native.so`threadStartCallback at yui.c:1574
```

```
  0xc27100f0: push {r4, r5, r6, r7, r8, r9, r10, lr}
  0xc27100f4: mov r7, r0
  0xc27100f8: ldr r8, [r7, #0x58]  <-- OK!
  0xc27100fc: ldr r9, [r7, #0x5c]   <-- OK!
  0xc2710100: mov r0, #4
  0xc2710104: mov r1, #12
  0xc2710108: ldr r3, [r7, r1]
  0xc271010c: sxtab r0, r3, r0
  0xc2710110: str r0, [r7, r1]
  0xc2710114: add r8, r8, #2
  0xc2710118: add r9, r9, #1
  0xc271011c: ldr r0, [r7, #0x54]  <-- OK!
  0xc2710120: cmn r0, #1
  0xc2710124: bne 0xc271013c
  0xc2710128: add r8, r8, #2
  0xc271012c: str r8, [r7, #0x58]  <-- OK!
  0xc2710130: add r9, r9, #1
  0xc2710134: str r9, [r7, #0x5c]  <-- OK!
  0xc2710138: pop {r4, r5, r6, r7, r8, r9, r10, pc}
  0xc271013c: mov r8, r0
  0xc2710140: sub r8, r8, #2
  0xc2710144: mov r0, r0
  0xc2710148: add r8, r8, #2
  0xc271014c: str r8, [r7, #0x58] <-- Crash!
  0xc2710150: add r9, r9, #3
  0xc2710154: str r9, [r7, #0x5c]
```

**Comment by FCare** [comment]
I think you do not need to push/pop r4,r5,r6 and r10 since you do not use it. It will save a bit of time.
I am seeing that you are doing a POP in between, after this POP, you should have return to the calling function, but the OK and crash information does not say where you are passing exactly. Can you point me the Assembly source code and not the disassembly?

Are you compiling in Thumb or in ARM mode?

**Comment by devmiyax** [comment]
This crash point is a part of code which dynamically generate in [CompileBlocks::EmmitCode](https://github.com/devmiyax/yabause/blob/dynarec/yabause/src/sh2_dynarec2/DynarecSh2.cpp#L761) 

This code is appended after a delay slot instruction and this is the crash point.
https://github.com/devmiyax/yabause/blob/dynarec/yabause/src/sh2_dynarec2/dynalib_arm.s#L266

And r0 is a argument of [((dynaFunc)((void*)(pBlock->code)))(m_pDynaSh2);](https://github.com/devmiyax/yabause/blob/dynarec/yabause/src/sh2_dynarec2/DynarecSh2.cpp#L1122)

**Comment by FCare** [comment]
The assembly code generation looks quite ok. But the separation between m_pDynaSh2 and SSH2 or MSH2 seems not to be clear. I think there is a mix here... Is it possible on your side to only start MSH2 and to not start SSH2 to test?

**Comment by devmiyax** [comment]
>start SSH2 to test?
No. SSH2 does not start yet.

**Comment by devmiyax** [comment]
OK
```
push {fp} 
add fp, sp, #0
sub sp, sp, #12
str r0, [fp, #-8]
sub sp, fp, #0
pop {fp}
bx lr
```

Bad
```
push {r4-r10, lr}   // push regs
mov r7, r0      // GenReg( r0 has adress of m_pDynaSh2)
LDR_PC r8       // PC
LDR_COUNT r9    // ClockCounter
STR_PC r8     // store PC to memory
STR_COUNT r9  // store COUNTER to memory
pop {r4-r10, pc}  // pop regs and resturn
```

What's the difference????

**Comment by FCare** [comment]
From what I have seen in your past dump, r7 is equal to 0x00000078. The only possibility to have this bad value is that r0 is equal to 0x00000078 when the code is executed.
For me, the issue does not code from the assembly code, which seems to be good. It comes from m_pDynaSh2 value which might be corrupted. That's why I sked if you were starting SH2.
I think you need to add a debug trace when you call the function with m_pDynaSh2 as parameter and check the value of this variable. If the value is ok, it might be also that R0 is corrupted between the function entry point and this code.

**Comment by devmiyax** [comment]
0xd02c40e4 <+1044>: ldr    r1, [r11, #-0xc]
    0xd02c40e8 <+1048>: ldr    r2, [r11, #-0x14]
    0xd02c40ec <+1052>: ldr    r3, [r2]
    0xd02c40f0 <+1056>: str    r0, [sp, #0x8]
    0xd02c40f4 <+1060>: mov    r0, r3
->0xd02c40f8 <+1064>: blx    r1
    0xd02c40fc <+1068>: ldr    r0, [r11, #-0x14]

**Comment by FCare** [comment]
It is not the full code, but let's try to understand what is done here. This code is branching to a code located at r11-0xC. I expect that m_pDynaSh2 address is located at r11-0x14. From what I've seen when a call is made, only r4 to r10 is saved on the stack. In case the code called with blx r1 is changing the value of r11, then the ldr r0, [r11, #-0x14] might adress a bad memory area, falling to a wrong m_pDynaSh2 address. Can you look where it jump after this blx r1, if it is save r11 and if it is changing it?

In http://infocenter.arm.com/help/topic/com.arm.doc.ihi0042f/IHI0042F_aapcs.pdf, it says that "A subroutine must preserve the contents of the registers r4-r8, r10, r11 and SP (and r9 in PCS variants that
designate r9 as v6)." it means that changing ldmfd  sp!, {r4-r10, pc} to ldmfd  sp!, {r4-r11, pc} and stmfd  sp!, {r4-r10, lr} to stmfd  sp!, {r4-r11, lr} might be able to fix the issue

**Comment by FCare** [comment]
I have checked that code generating in ARM mode are using r11 as a fp and THUMB mode is using r7 as fp. The code here is in THUMB mode, but some code are generated from the C, which goes to ARM mode. That's why there is a blx call here, it is switching between ARM an THUMB. 
So there is a high probability that r11 will change. 

Definitively, you have to update from r4-r10 to r4-r11

**Comment by devmiyax** [comment]
it seems cacheflush() is needed. Now it works fine! 

https://minghuasweblog.wordpress.com/2013/03/29/arm-cache-flush-on-mmapd-buffers-with-clear-cache/

**Comment by FCare** [comment]
Good catch :-)
Anyway, I would recommand to add r11 to the saved register list. It is expected to be saved by subroutines. You might experience some other side effects or bugs here.

**Comment by devmiyax** [comment]
cacheflush sloves this issue.
