### ISSUE TITLE
Sonic 3D Flickies Island                                                                                        

### ISSUE THREAD

**Issue by devmiyax** [devmiyax/yabause#673]
version:2.9.0-PRO
device:X2-HT
cpu_type:3
video_type:1
comment:transparent does not work
[state file](http://www.uoyabause.org//system/reports/state_files/000/004/899/original/GS-9143_2019_10_30_08_31_34.zip)
![screenshot](http://www.uoyabause.org//system/reports/screenshots/000/004/899/original/screenshot.png?1572391898)

**Comment by nicolas-charrier** [comment]
Special priority per tile doesn't work in v2.9.0. It was correct in v2.8.1.

The same problem is visible in Thunder Force 4 in Thunder force gold pack 2.
![image](https://user-images.githubusercontent.com/7624262/68117775-923b0300-fefe-11e9-8e03-870b87d9f93c.png)
![image](https://user-images.githubusercontent.com/7624262/68117787-9c5d0180-fefe-11e9-8708-40032edaac90.png)

Sonic 3D is using special priority on NBG0 layer to change some tiles priority from 2 to 3, displaying them over Sonic sprite (priority 2).
This setting is not displayed in VDP2 debug window (but its use is confirmed by Fcare in Kronos bug report [462](https://github.com/FCare/Kronos/issues/462) ), maybe because it's set by an interrupt in the display period.

Tested with japanese CD and real bios on Windows versions.

**Comment by devmiyax** [comment]
it will be fixed in 2.10.0

![image](https://user-images.githubusercontent.com/1174152/68120519-ec60b600-ff48-11e9-8a54-5405767b50de.png)

**Comment by nicolas-charrier** [comment]
In Windows v2.10.0, the display is fixed in Sonic 3D, but it is still incorrect in Thunder Force gold pack 2.

**Comment by devmiyax** [comment]
Close this issue and add
https://github.com/devmiyax/yabause/issues/755
