### ISSUE TITLE
[Albert Odyssey] Transparencies problem and missing characters

### ISSUE THREAD

**Issue by BenjaminSiskoo** [devmiyax/yabause#88]
Left Picture : Yabause Devmiyax 05.05.2016 (Software)
Right Picture : Yabause Devmiyax 05.05.2016 (OpenGl)

Clouds are not transparent.

![albert odyssey_mainscreen](https://cloud.githubusercontent.com/assets/12481242/11761319/d38e0d00-a0bd-11e5-933d-40096ec9523f.PNG)

Missing characters and some fire effects.

![albert odyssey_intro](https://cloud.githubusercontent.com/assets/12481242/11761318/d36bc7b8-a0bd-11e5-933b-a28fadf35416.PNG)

**Comment by BenjaminSiskoo** [comment]
Missing characters fixed, trhanks

**Comment by FCare** [comment]
It seems transparency issue is due to color offset implementation for NORMAL shaders. If in the NORMAL shader you remove the add of the color offset, then transparency is ok.

**Comment by BenjaminSiskoo** [comment]
Left Picture : UoYabause 0.4.1
Right Picture : UoYabause (FCare fork)

![albertodyssey](https://cloud.githubusercontent.com/assets/12481242/22854091/60162bc4-f066-11e6-95d6-55601fae68b4.JPG)

**Comment by FCare** [comment]
For information, I have fixed it here:
https://github.com/FCare/piYabause/commit/0104d35f62d43e73d5b1a82635ba719f1af3b5bc

It seems in that case that alpha is applied twice, making the clouds more dark.
I also have this one: 
https://github.com/FCare/piYabause/commit/9e12733a33cece01b0b2c9af967c60d3d1fcd8c2

I think it has quite no impact in any games since color offset value are always quite the same for all color component.

**Comment by BenjaminSiskoo** [comment]
Sounds good.
